apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: public.ecr.aws/y5d0d8s1/project:latest
          ports:
            - containerPort: 80
