apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: apiserver
  labels:
    app: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: 988020867216.dkr.ecr.us-east-1.amazonaws.com/request-thunder/api-server:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_CONNECTION_URI
            - name: NOTIFICATION_URL
              valueFrom:
                configMapKeyRef:
                  name: rt-configmap
                  key: NOTIFICATION_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: rt-configmap
                  key: PORT
            - name: APPLICATION_HOST
              valueFrom:
                configMapKeyRef:
                  name: rt-configmap
                  key: APPLICATION_HOST
            - name: CAPTCHA_KEY
              valueFrom:
                configMapKeyRef:
                  name: rt-configmap
                  key: CAPTCHA_KEY
            - name: WEBHOOK
              valueFrom:
                configMapKeyRef:
                  name: rt-configmap
                  key: WEBHOOK
            - name: SES_REGION
              valueFrom:
                configMapKeyRef:
                  name: rt-configmap
                  key: SES_REGION
            - name: SES_EMAIL_FROM
              valueFrom:
                configMapKeyRef:
                  name: rt-configmap
                  key: SES_EMAIL_FROM
            - name: SES_CONFIG_SET_NAME
              valueFrom:
                configMapKeyRef:
                  name: rt-configmap
                  key: SES_CONFIG_SET_NAME
