apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
        - name: runner
          image: 988020867216.dkr.ecr.us-east-1.amazonaws.com/request-thunder/runner:v1.0.0
          ports:
            - containerPort: 80
