---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ui-depoly
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: 988020867216.dkr.ecr.us-east-1.amazonaws.com/request-thunder/ui:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80